version: "3.9"

services:
  jupiter_db:
    image: postgres
    restart: always
    container_name: jupiter_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: Jupiter
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
